// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 信息类型
type MsgType int32

const (
	MsgType_Msg_Auth           MsgType = 0
	MsgType_Msg_AuthAck        MsgType = 1
	MsgType_Msg_UnAuth         MsgType = 2
	MsgType_Msg_Ping           MsgType = 3
	MsgType_Msg_Pong           MsgType = 4
	MsgType_Msg_OpenPort       MsgType = 5
	MsgType_Msg_OpenPortAck    MsgType = 6
	MsgType_Msg_ClosePort      MsgType = 7
	MsgType_Msg_ClosePortAck   MsgType = 8
	MsgType_Msg_Data           MsgType = 9
	MsgType_Msg_DataAck        MsgType = 10
	MsgType_Msg_GetConfig      MsgType = 11
	MsgType_Msg_GetConfigAck   MsgType = 12
	MsgType_Msg_GetPortList    MsgType = 13
	MsgType_Msg_GetPortListAck MsgType = 14
	MsgType_Msg_State          MsgType = 15
)

var MsgType_name = map[int32]string{
	0:  "Msg_Auth",
	1:  "Msg_AuthAck",
	2:  "Msg_UnAuth",
	3:  "Msg_Ping",
	4:  "Msg_Pong",
	5:  "Msg_OpenPort",
	6:  "Msg_OpenPortAck",
	7:  "Msg_ClosePort",
	8:  "Msg_ClosePortAck",
	9:  "Msg_Data",
	10: "Msg_DataAck",
	11: "Msg_GetConfig",
	12: "Msg_GetConfigAck",
	13: "Msg_GetPortList",
	14: "Msg_GetPortListAck",
	15: "Msg_State",
}

var MsgType_value = map[string]int32{
	"Msg_Auth":           0,
	"Msg_AuthAck":        1,
	"Msg_UnAuth":         2,
	"Msg_Ping":           3,
	"Msg_Pong":           4,
	"Msg_OpenPort":       5,
	"Msg_OpenPortAck":    6,
	"Msg_ClosePort":      7,
	"Msg_ClosePortAck":   8,
	"Msg_Data":           9,
	"Msg_DataAck":        10,
	"Msg_GetConfig":      11,
	"Msg_GetConfigAck":   12,
	"Msg_GetPortList":    13,
	"Msg_GetPortListAck": 14,
	"Msg_State":          15,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type MsgAuth struct {
	ClientId             uint64   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAuth) Reset()         { *m = MsgAuth{} }
func (m *MsgAuth) String() string { return proto.CompactTextString(m) }
func (*MsgAuth) ProtoMessage()    {}
func (*MsgAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *MsgAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAuth.Unmarshal(m, b)
}
func (m *MsgAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAuth.Marshal(b, m, deterministic)
}
func (m *MsgAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuth.Merge(m, src)
}
func (m *MsgAuth) XXX_Size() int {
	return xxx_messageInfo_MsgAuth.Size(m)
}
func (m *MsgAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuth.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuth proto.InternalMessageInfo

func (m *MsgAuth) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

type MsgAuthAck struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Tip                  string   `protobuf:"bytes,2,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgAuthAck) Reset()         { *m = MsgAuthAck{} }
func (m *MsgAuthAck) String() string { return proto.CompactTextString(m) }
func (*MsgAuthAck) ProtoMessage()    {}
func (*MsgAuthAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *MsgAuthAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAuthAck.Unmarshal(m, b)
}
func (m *MsgAuthAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAuthAck.Marshal(b, m, deterministic)
}
func (m *MsgAuthAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthAck.Merge(m, src)
}
func (m *MsgAuthAck) XXX_Size() int {
	return xxx_messageInfo_MsgAuthAck.Size(m)
}
func (m *MsgAuthAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthAck proto.InternalMessageInfo

func (m *MsgAuthAck) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MsgAuthAck) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type MsgConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Baud                 uint32   `protobuf:"varint,2,opt,name=baud,proto3" json:"baud,omitempty"`
	DataBit              uint32   `protobuf:"varint,3,opt,name=data_bit,json=dataBit,proto3" json:"data_bit,omitempty"`
	DataParity           uint32   `protobuf:"varint,4,opt,name=data_parity,json=dataParity,proto3" json:"data_parity,omitempty"`
	StopBit              uint32   `protobuf:"varint,5,opt,name=stop_bit,json=stopBit,proto3" json:"stop_bit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgConfig) Reset()         { *m = MsgConfig{} }
func (m *MsgConfig) String() string { return proto.CompactTextString(m) }
func (*MsgConfig) ProtoMessage()    {}
func (*MsgConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *MsgConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgConfig.Unmarshal(m, b)
}
func (m *MsgConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgConfig.Marshal(b, m, deterministic)
}
func (m *MsgConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfig.Merge(m, src)
}
func (m *MsgConfig) XXX_Size() int {
	return xxx_messageInfo_MsgConfig.Size(m)
}
func (m *MsgConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfig proto.InternalMessageInfo

func (m *MsgConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgConfig) GetBaud() uint32 {
	if m != nil {
		return m.Baud
	}
	return 0
}

func (m *MsgConfig) GetDataBit() uint32 {
	if m != nil {
		return m.DataBit
	}
	return 0
}

func (m *MsgConfig) GetDataParity() uint32 {
	if m != nil {
		return m.DataParity
	}
	return 0
}

func (m *MsgConfig) GetStopBit() uint32 {
	if m != nil {
		return m.StopBit
	}
	return 0
}

type MsgOpenPort struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config               *MsgConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgOpenPort) Reset()         { *m = MsgOpenPort{} }
func (m *MsgOpenPort) String() string { return proto.CompactTextString(m) }
func (*MsgOpenPort) ProtoMessage()    {}
func (*MsgOpenPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *MsgOpenPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgOpenPort.Unmarshal(m, b)
}
func (m *MsgOpenPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgOpenPort.Marshal(b, m, deterministic)
}
func (m *MsgOpenPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenPort.Merge(m, src)
}
func (m *MsgOpenPort) XXX_Size() int {
	return xxx_messageInfo_MsgOpenPort.Size(m)
}
func (m *MsgOpenPort) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenPort.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenPort proto.InternalMessageInfo

func (m *MsgOpenPort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgOpenPort) GetConfig() *MsgConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type MsgOpenPortAck struct {
	Result               bool       `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tip                  string     `protobuf:"bytes,3,opt,name=tip,proto3" json:"tip,omitempty"`
	Config               *MsgConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgOpenPortAck) Reset()         { *m = MsgOpenPortAck{} }
func (m *MsgOpenPortAck) String() string { return proto.CompactTextString(m) }
func (*MsgOpenPortAck) ProtoMessage()    {}
func (*MsgOpenPortAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *MsgOpenPortAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgOpenPortAck.Unmarshal(m, b)
}
func (m *MsgOpenPortAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgOpenPortAck.Marshal(b, m, deterministic)
}
func (m *MsgOpenPortAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenPortAck.Merge(m, src)
}
func (m *MsgOpenPortAck) XXX_Size() int {
	return xxx_messageInfo_MsgOpenPortAck.Size(m)
}
func (m *MsgOpenPortAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenPortAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenPortAck proto.InternalMessageInfo

func (m *MsgOpenPortAck) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MsgOpenPortAck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgOpenPortAck) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

func (m *MsgOpenPortAck) GetConfig() *MsgConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type MsgClosePort struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClosePort) Reset()         { *m = MsgClosePort{} }
func (m *MsgClosePort) String() string { return proto.CompactTextString(m) }
func (*MsgClosePort) ProtoMessage()    {}
func (*MsgClosePort) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *MsgClosePort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClosePort.Unmarshal(m, b)
}
func (m *MsgClosePort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClosePort.Marshal(b, m, deterministic)
}
func (m *MsgClosePort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClosePort.Merge(m, src)
}
func (m *MsgClosePort) XXX_Size() int {
	return xxx_messageInfo_MsgClosePort.Size(m)
}
func (m *MsgClosePort) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClosePort.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClosePort proto.InternalMessageInfo

func (m *MsgClosePort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgClosePortAck struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tip                  string   `protobuf:"bytes,3,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClosePortAck) Reset()         { *m = MsgClosePortAck{} }
func (m *MsgClosePortAck) String() string { return proto.CompactTextString(m) }
func (*MsgClosePortAck) ProtoMessage()    {}
func (*MsgClosePortAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *MsgClosePortAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClosePortAck.Unmarshal(m, b)
}
func (m *MsgClosePortAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClosePortAck.Marshal(b, m, deterministic)
}
func (m *MsgClosePortAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClosePortAck.Merge(m, src)
}
func (m *MsgClosePortAck) XXX_Size() int {
	return xxx_messageInfo_MsgClosePortAck.Size(m)
}
func (m *MsgClosePortAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClosePortAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClosePortAck proto.InternalMessageInfo

func (m *MsgClosePortAck) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MsgClosePortAck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgClosePortAck) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type MsgData struct {
	Sn                   uint32   `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NeedAck              bool     `protobuf:"varint,3,opt,name=need_ack,json=needAck,proto3" json:"need_ack,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgData) Reset()         { *m = MsgData{} }
func (m *MsgData) String() string { return proto.CompactTextString(m) }
func (*MsgData) ProtoMessage()    {}
func (*MsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *MsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgData.Unmarshal(m, b)
}
func (m *MsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgData.Marshal(b, m, deterministic)
}
func (m *MsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgData.Merge(m, src)
}
func (m *MsgData) XXX_Size() int {
	return xxx_messageInfo_MsgData.Size(m)
}
func (m *MsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgData proto.InternalMessageInfo

func (m *MsgData) GetSn() uint32 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *MsgData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgData) GetNeedAck() bool {
	if m != nil {
		return m.NeedAck
	}
	return false
}

func (m *MsgData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 可选
type MsgDataAck struct {
	Sn                   uint32   `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Result               bool     `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDataAck) Reset()         { *m = MsgDataAck{} }
func (m *MsgDataAck) String() string { return proto.CompactTextString(m) }
func (*MsgDataAck) ProtoMessage()    {}
func (*MsgDataAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *MsgDataAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDataAck.Unmarshal(m, b)
}
func (m *MsgDataAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDataAck.Marshal(b, m, deterministic)
}
func (m *MsgDataAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDataAck.Merge(m, src)
}
func (m *MsgDataAck) XXX_Size() int {
	return xxx_messageInfo_MsgDataAck.Size(m)
}
func (m *MsgDataAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDataAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDataAck proto.InternalMessageInfo

func (m *MsgDataAck) GetSn() uint32 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *MsgDataAck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgDataAck) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type MsgGetConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgGetConfig) Reset()         { *m = MsgGetConfig{} }
func (m *MsgGetConfig) String() string { return proto.CompactTextString(m) }
func (*MsgGetConfig) ProtoMessage()    {}
func (*MsgGetConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *MsgGetConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgGetConfig.Unmarshal(m, b)
}
func (m *MsgGetConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgGetConfig.Marshal(b, m, deterministic)
}
func (m *MsgGetConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetConfig.Merge(m, src)
}
func (m *MsgGetConfig) XXX_Size() int {
	return xxx_messageInfo_MsgGetConfig.Size(m)
}
func (m *MsgGetConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetConfig proto.InternalMessageInfo

func (m *MsgGetConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgGetConfigAck struct {
	Result               bool       `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tip                  string     `protobuf:"bytes,3,opt,name=tip,proto3" json:"tip,omitempty"`
	Config               *MsgConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgGetConfigAck) Reset()         { *m = MsgGetConfigAck{} }
func (m *MsgGetConfigAck) String() string { return proto.CompactTextString(m) }
func (*MsgGetConfigAck) ProtoMessage()    {}
func (*MsgGetConfigAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *MsgGetConfigAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgGetConfigAck.Unmarshal(m, b)
}
func (m *MsgGetConfigAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgGetConfigAck.Marshal(b, m, deterministic)
}
func (m *MsgGetConfigAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetConfigAck.Merge(m, src)
}
func (m *MsgGetConfigAck) XXX_Size() int {
	return xxx_messageInfo_MsgGetConfigAck.Size(m)
}
func (m *MsgGetConfigAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetConfigAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetConfigAck proto.InternalMessageInfo

func (m *MsgGetConfigAck) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MsgGetConfigAck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgGetConfigAck) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

func (m *MsgGetConfigAck) GetConfig() *MsgConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type MsgGetPortListAck struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Tip                  string   `protobuf:"bytes,2,opt,name=tip,proto3" json:"tip,omitempty"`
	PortList             []string `protobuf:"bytes,3,rep,name=port_list,json=portList,proto3" json:"port_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgGetPortListAck) Reset()         { *m = MsgGetPortListAck{} }
func (m *MsgGetPortListAck) String() string { return proto.CompactTextString(m) }
func (*MsgGetPortListAck) ProtoMessage()    {}
func (*MsgGetPortListAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *MsgGetPortListAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgGetPortListAck.Unmarshal(m, b)
}
func (m *MsgGetPortListAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgGetPortListAck.Marshal(b, m, deterministic)
}
func (m *MsgGetPortListAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGetPortListAck.Merge(m, src)
}
func (m *MsgGetPortListAck) XXX_Size() int {
	return xxx_messageInfo_MsgGetPortListAck.Size(m)
}
func (m *MsgGetPortListAck) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGetPortListAck.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGetPortListAck proto.InternalMessageInfo

func (m *MsgGetPortListAck) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MsgGetPortListAck) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

func (m *MsgGetPortListAck) GetPortList() []string {
	if m != nil {
		return m.PortList
	}
	return nil
}

type MsgState struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Close                bool     `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgState) Reset()         { *m = MsgState{} }
func (m *MsgState) String() string { return proto.CompactTextString(m) }
func (*MsgState) ProtoMessage()    {}
func (*MsgState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *MsgState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgState.Unmarshal(m, b)
}
func (m *MsgState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgState.Marshal(b, m, deterministic)
}
func (m *MsgState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgState.Merge(m, src)
}
func (m *MsgState) XXX_Size() int {
	return xxx_messageInfo_MsgState.Size(m)
}
func (m *MsgState) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgState.DiscardUnknown(m)
}

var xxx_messageInfo_MsgState proto.InternalMessageInfo

func (m *MsgState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgState) GetClose() bool {
	if m != nil {
		return m.Close
	}
	return false
}

type MsgClientFrame struct {
	MsgType              MsgType       `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=message.MsgType" json:"msg_type,omitempty"`
	SrcId                uint64        `protobuf:"varint,2,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	MsgAuth              *MsgAuth      `protobuf:"bytes,3,opt,name=msg_auth,json=msgAuth,proto3" json:"msg_auth,omitempty"`
	MsgOpenCom           *MsgOpenPort  `protobuf:"bytes,4,opt,name=msg_open_com,json=msgOpenCom,proto3" json:"msg_open_com,omitempty"`
	MsgCloseCom          *MsgClosePort `protobuf:"bytes,5,opt,name=msg_close_com,json=msgCloseCom,proto3" json:"msg_close_com,omitempty"`
	MsgData              *MsgData      `protobuf:"bytes,6,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	MsgGetConfig         *MsgGetConfig `protobuf:"bytes,7,opt,name=msg_get_config,json=msgGetConfig,proto3" json:"msg_get_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgClientFrame) Reset()         { *m = MsgClientFrame{} }
func (m *MsgClientFrame) String() string { return proto.CompactTextString(m) }
func (*MsgClientFrame) ProtoMessage()    {}
func (*MsgClientFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *MsgClientFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClientFrame.Unmarshal(m, b)
}
func (m *MsgClientFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClientFrame.Marshal(b, m, deterministic)
}
func (m *MsgClientFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClientFrame.Merge(m, src)
}
func (m *MsgClientFrame) XXX_Size() int {
	return xxx_messageInfo_MsgClientFrame.Size(m)
}
func (m *MsgClientFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClientFrame.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClientFrame proto.InternalMessageInfo

func (m *MsgClientFrame) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_Msg_Auth
}

func (m *MsgClientFrame) GetSrcId() uint64 {
	if m != nil {
		return m.SrcId
	}
	return 0
}

func (m *MsgClientFrame) GetMsgAuth() *MsgAuth {
	if m != nil {
		return m.MsgAuth
	}
	return nil
}

func (m *MsgClientFrame) GetMsgOpenCom() *MsgOpenPort {
	if m != nil {
		return m.MsgOpenCom
	}
	return nil
}

func (m *MsgClientFrame) GetMsgCloseCom() *MsgClosePort {
	if m != nil {
		return m.MsgCloseCom
	}
	return nil
}

func (m *MsgClientFrame) GetMsgData() *MsgData {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *MsgClientFrame) GetMsgGetConfig() *MsgGetConfig {
	if m != nil {
		return m.MsgGetConfig
	}
	return nil
}

// 服务端返回的普通消息
type MsgServerFrame struct {
	MsgType              MsgType            `protobuf:"varint,31,opt,name=msg_type,json=msgType,proto3,enum=message.MsgType" json:"msg_type,omitempty"`
	SrcId                uint64             `protobuf:"varint,32,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	MsgAuthAck           *MsgAuthAck        `protobuf:"bytes,33,opt,name=msg_auth_ack,json=msgAuthAck,proto3" json:"msg_auth_ack,omitempty"`
	MsgOpenPortAck       *MsgOpenPortAck    `protobuf:"bytes,34,opt,name=msg_open_port_ack,json=msgOpenPortAck,proto3" json:"msg_open_port_ack,omitempty"`
	MsgClosePortAck      *MsgClosePortAck   `protobuf:"bytes,35,opt,name=msg_close_port_ack,json=msgClosePortAck,proto3" json:"msg_close_port_ack,omitempty"`
	MsgData              *MsgData           `protobuf:"bytes,36,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	MsgDataAck           *MsgDataAck        `protobuf:"bytes,37,opt,name=msg_data_ack,json=msgDataAck,proto3" json:"msg_data_ack,omitempty"`
	MsgGetConfigAck      *MsgGetConfigAck   `protobuf:"bytes,38,opt,name=msg_get_config_ack,json=msgGetConfigAck,proto3" json:"msg_get_config_ack,omitempty"`
	MsgPortListAck       *MsgGetPortListAck `protobuf:"bytes,39,opt,name=msg_port_list_ack,json=msgPortListAck,proto3" json:"msg_port_list_ack,omitempty"`
	MsgState             *MsgState          `protobuf:"bytes,40,opt,name=msg_state,json=msgState,proto3" json:"msg_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MsgServerFrame) Reset()         { *m = MsgServerFrame{} }
func (m *MsgServerFrame) String() string { return proto.CompactTextString(m) }
func (*MsgServerFrame) ProtoMessage()    {}
func (*MsgServerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *MsgServerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgServerFrame.Unmarshal(m, b)
}
func (m *MsgServerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgServerFrame.Marshal(b, m, deterministic)
}
func (m *MsgServerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgServerFrame.Merge(m, src)
}
func (m *MsgServerFrame) XXX_Size() int {
	return xxx_messageInfo_MsgServerFrame.Size(m)
}
func (m *MsgServerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgServerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_MsgServerFrame proto.InternalMessageInfo

func (m *MsgServerFrame) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_Msg_Auth
}

func (m *MsgServerFrame) GetSrcId() uint64 {
	if m != nil {
		return m.SrcId
	}
	return 0
}

func (m *MsgServerFrame) GetMsgAuthAck() *MsgAuthAck {
	if m != nil {
		return m.MsgAuthAck
	}
	return nil
}

func (m *MsgServerFrame) GetMsgOpenPortAck() *MsgOpenPortAck {
	if m != nil {
		return m.MsgOpenPortAck
	}
	return nil
}

func (m *MsgServerFrame) GetMsgClosePortAck() *MsgClosePortAck {
	if m != nil {
		return m.MsgClosePortAck
	}
	return nil
}

func (m *MsgServerFrame) GetMsgData() *MsgData {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *MsgServerFrame) GetMsgDataAck() *MsgDataAck {
	if m != nil {
		return m.MsgDataAck
	}
	return nil
}

func (m *MsgServerFrame) GetMsgGetConfigAck() *MsgGetConfigAck {
	if m != nil {
		return m.MsgGetConfigAck
	}
	return nil
}

func (m *MsgServerFrame) GetMsgPortListAck() *MsgGetPortListAck {
	if m != nil {
		return m.MsgPortListAck
	}
	return nil
}

func (m *MsgServerFrame) GetMsgState() *MsgState {
	if m != nil {
		return m.MsgState
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*MsgAuth)(nil), "message.MsgAuth")
	proto.RegisterType((*MsgAuthAck)(nil), "message.MsgAuthAck")
	proto.RegisterType((*MsgConfig)(nil), "message.MsgConfig")
	proto.RegisterType((*MsgOpenPort)(nil), "message.MsgOpenPort")
	proto.RegisterType((*MsgOpenPortAck)(nil), "message.MsgOpenPortAck")
	proto.RegisterType((*MsgClosePort)(nil), "message.MsgClosePort")
	proto.RegisterType((*MsgClosePortAck)(nil), "message.MsgClosePortAck")
	proto.RegisterType((*MsgData)(nil), "message.MsgData")
	proto.RegisterType((*MsgDataAck)(nil), "message.MsgDataAck")
	proto.RegisterType((*MsgGetConfig)(nil), "message.MsgGetConfig")
	proto.RegisterType((*MsgGetConfigAck)(nil), "message.MsgGetConfigAck")
	proto.RegisterType((*MsgGetPortListAck)(nil), "message.MsgGetPortListAck")
	proto.RegisterType((*MsgState)(nil), "message.MsgState")
	proto.RegisterType((*MsgClientFrame)(nil), "message.MsgClientFrame")
	proto.RegisterType((*MsgServerFrame)(nil), "message.MsgServerFrame")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0x6e, 0x23, 0x45,
	0x10, 0xc5, 0xe3, 0xdb, 0xb8, 0x7c, 0x6b, 0xf7, 0x66, 0x17, 0x2f, 0x3c, 0x6c, 0x18, 0x60, 0xb1,
	0x16, 0xc9, 0x0f, 0x0b, 0xac, 0x84, 0x78, 0x4a, 0x42, 0x80, 0x48, 0x58, 0x89, 0x3a, 0xf0, 0x82,
	0x90, 0x46, 0x93, 0x71, 0x33, 0x19, 0xc5, 0x73, 0xd1, 0x74, 0x1b, 0x29, 0xf0, 0x07, 0x7c, 0x09,
	0x9f, 0xc0, 0xd7, 0xf0, 0x2d, 0xa8, 0x6a, 0x7a, 0x26, 0xed, 0x4b, 0x48, 0x10, 0xd2, 0xbe, 0x75,
	0x95, 0xab, 0x4e, 0x55, 0x9d, 0xba, 0x8c, 0xa1, 0x97, 0xa8, 0x68, 0x9e, 0x17, 0x99, 0xce, 0x78,
	0x37, 0x91, 0x4a, 0x05, 0x91, 0xf4, 0x5e, 0x42, 0x77, 0xa1, 0xa2, 0xa3, 0xb5, 0xbe, 0xe6, 0xef,
	0x43, 0x2f, 0x5c, 0xc5, 0x32, 0xd5, 0x7e, 0xbc, 0x9c, 0x36, 0x0e, 0x1b, 0xb3, 0x96, 0x70, 0x4b,
	0xc5, 0xd9, 0xd2, 0x7b, 0x03, 0x60, 0xec, 0x8e, 0xc2, 0x1b, 0xfe, 0x0c, 0x3a, 0x85, 0x54, 0xeb,
	0x95, 0x26, 0x3b, 0x57, 0x18, 0x89, 0x33, 0x68, 0xea, 0x38, 0x9f, 0x3a, 0x87, 0x8d, 0x59, 0x4f,
	0xe0, 0xd3, 0xfb, 0xa3, 0x01, 0xbd, 0x85, 0x8a, 0x4e, 0xb2, 0xf4, 0x97, 0x38, 0xe2, 0x1c, 0x5a,
	0x69, 0x90, 0x48, 0xf2, 0xea, 0x09, 0x7a, 0xa3, 0xee, 0x2a, 0x58, 0x2f, 0xc9, 0x69, 0x28, 0xe8,
	0xcd, 0x9f, 0x83, 0xbb, 0x0c, 0x74, 0xe0, 0x5f, 0xc5, 0x7a, 0xda, 0x24, 0x7d, 0x17, 0xe5, 0xe3,
	0x58, 0xf3, 0x17, 0xd0, 0xa7, 0x9f, 0xf2, 0xa0, 0x88, 0xf5, 0xed, 0xb4, 0x45, 0xbf, 0x02, 0xaa,
	0x2e, 0x48, 0x83, 0xbe, 0x4a, 0x67, 0x39, 0xf9, 0xb6, 0x4b, 0x5f, 0x94, 0x8f, 0x63, 0xed, 0x2d,
	0xa0, 0xbf, 0x50, 0xd1, 0x79, 0x2e, 0xd3, 0x8b, 0xac, 0xd0, 0x7b, 0xb3, 0x79, 0x05, 0x9d, 0x90,
	0x72, 0xa5, 0x7c, 0xfa, 0xaf, 0xf9, 0xdc, 0x30, 0x35, 0xaf, 0xab, 0x10, 0xc6, 0xc2, 0xfb, 0x0d,
	0x46, 0x16, 0xdc, 0xbf, 0xf1, 0x52, 0x45, 0x72, 0xac, 0x48, 0x86, 0xab, 0x66, 0xcd, 0x95, 0x15,
	0xbb, 0xf5, 0x60, 0x6c, 0x0f, 0x06, 0xa8, 0x5c, 0x65, 0x4a, 0xde, 0x57, 0x8b, 0x77, 0x0e, 0x63,
	0xdb, 0xe6, 0x7f, 0x27, 0xe8, 0xfd, 0x4c, 0xc3, 0xf2, 0x75, 0xa0, 0x03, 0x3e, 0x02, 0x47, 0xa5,
	0x04, 0x32, 0x14, 0x8e, 0x4a, 0xf7, 0x02, 0x3c, 0x07, 0x37, 0x95, 0x72, 0xe9, 0x07, 0xe1, 0x0d,
	0xa1, 0xb8, 0xa2, 0x8b, 0x32, 0xe6, 0xc1, 0xa1, 0x85, 0x2d, 0xa3, 0x42, 0x07, 0x82, 0xde, 0xde,
	0x77, 0x34, 0x62, 0x88, 0x8e, 0x16, 0x8f, 0x09, 0x70, 0x57, 0x4d, 0xd3, 0xae, 0xc6, 0x90, 0xf3,
	0xad, 0xd4, 0xf7, 0x8f, 0x9d, 0xf7, 0x3b, 0x91, 0x53, 0xdb, 0xbc, 0xdd, 0xee, 0xfd, 0x04, 0x93,
	0x32, 0x38, 0xf6, 0xe5, 0xfb, 0x58, 0xe9, 0xff, 0xb4, 0x54, 0xb8, 0xa9, 0x79, 0x56, 0x68, 0x7f,
	0x15, 0x2b, 0x2c, 0xbd, 0x39, 0xeb, 0x09, 0x37, 0x37, 0x48, 0xde, 0xe7, 0xe0, 0x2e, 0x54, 0x74,
	0xa9, 0x03, 0x2d, 0xf7, 0x4e, 0xf8, 0x01, 0xb4, 0x43, 0x1c, 0x09, 0x02, 0x74, 0x45, 0x29, 0x78,
	0x7f, 0x3b, 0x34, 0xcc, 0x27, 0xb4, 0xef, 0xdf, 0x14, 0x68, 0xf8, 0x29, 0xb8, 0x89, 0x8a, 0x7c,
	0x7d, 0x9b, 0x97, 0x00, 0xa3, 0xd7, 0xcc, 0x2e, 0xe9, 0x87, 0xdb, 0x5c, 0x8a, 0x6e, 0x52, 0x3e,
	0xf8, 0x53, 0xe8, 0xa8, 0x22, 0xc4, 0xcb, 0xe1, 0xd0, 0xe5, 0x68, 0xab, 0x22, 0x3c, 0x5b, 0x56,
	0x18, 0xc1, 0x5a, 0x5f, 0x13, 0x57, 0xfd, 0x4d, 0x0c, 0xbc, 0x27, 0x84, 0x41, 0x07, 0xe8, 0x0d,
	0x0c, 0xd0, 0x38, 0xcb, 0x65, 0xea, 0x87, 0x59, 0x62, 0x78, 0x3c, 0xb0, 0x1d, 0xaa, 0x65, 0x13,
	0x90, 0x94, 0xc2, 0x49, 0x96, 0xf0, 0x2f, 0x61, 0x88, 0x7e, 0x54, 0x08, 0x39, 0xb6, 0xc9, 0xf1,
	0xe9, 0x46, 0x03, 0xaa, 0x2d, 0x10, 0xfd, 0xc4, 0x48, 0xe8, 0x6a, 0xf2, 0xa3, 0x59, 0xec, 0xec,
	0xe6, 0x87, 0xc3, 0x48, 0xf9, 0xd1, 0xcc, 0x7f, 0x05, 0x23, 0x34, 0x8e, 0xa4, 0xf6, 0x4d, 0xa7,
	0xbb, 0xbb, 0x81, 0xea, 0x89, 0x12, 0x58, 0x4c, 0x2d, 0x79, 0x7f, 0xb5, 0x88, 0xe0, 0x4b, 0x59,
	0xfc, 0x2a, 0x8b, 0x5d, 0x82, 0x5f, 0x3c, 0x9e, 0xe0, 0x43, 0x9b, 0xe0, 0x2f, 0x4a, 0xce, 0x90,
	0x60, 0xda, 0xb3, 0x0f, 0x28, 0xa3, 0x27, 0xdb, 0x24, 0x1f, 0x85, 0x37, 0x44, 0x59, 0x75, 0xc0,
	0x8f, 0x61, 0x52, 0x53, 0x4d, 0xa3, 0x84, 0xbe, 0x1e, 0xf9, 0xbe, 0xbb, 0x8f, 0x6f, 0xf4, 0x1f,
	0x25, 0x9b, 0xc7, 0xee, 0x14, 0xf8, 0x1d, 0xed, 0x35, 0xc8, 0x87, 0x04, 0x32, 0xdd, 0xcb, 0x3d,
	0xa2, 0x8c, 0x93, 0xad, 0x93, 0x64, 0xb7, 0xe0, 0xa3, 0x87, 0x5a, 0x60, 0xca, 0xa5, 0x2f, 0x00,
	0x46, 0xfb, 0x78, 0xb7, 0x5c, 0x73, 0x40, 0xa8, 0xdc, 0xea, 0x98, 0x98, 0x54, 0xef, 0x3a, 0x47,
	0xce, 0x2f, 0x77, 0x53, 0xb5, 0xef, 0x01, 0xa5, 0xba, 0x71, 0x20, 0x4e, 0x4b, 0xd6, 0xea, 0xdd,
	0x23, 0x94, 0x4f, 0x08, 0xe5, 0xbd, 0x2d, 0x14, 0x6b, 0xb1, 0x89, 0x38, 0x7b, 0xd1, 0xe7, 0xf4,
	0x25, 0xf6, 0x15, 0xae, 0xe8, 0x74, 0x46, 0xee, 0x13, 0xdb, 0x9d, 0x76, 0x57, 0x20, 0x2b, 0xf4,
	0x7a, 0xf5, 0xa7, 0x43, 0x77, 0x97, 0xc6, 0x60, 0x40, 0xdb, 0xed, 0x63, 0x1f, 0xd9, 0x3b, 0x7c,
	0x4c, 0x1f, 0x34, 0xdf, 0x74, 0x95, 0x35, 0xf8, 0x88, 0x6e, 0xa8, 0xff, 0x63, 0x4a, 0x06, 0x4e,
	0x65, 0x7e, 0x11, 0xa7, 0x11, 0x6b, 0xd6, 0x52, 0x96, 0x46, 0xac, 0xc5, 0x19, 0x5d, 0x49, 0xbf,
	0x6a, 0x29, 0x6b, 0xf3, 0x27, 0x74, 0x13, 0x7d, 0xab, 0xc9, 0xac, 0xc3, 0x27, 0x30, 0x44, 0x65,
	0xdd, 0x33, 0xd6, 0xe5, 0x07, 0xc0, 0x36, 0x54, 0x68, 0xe8, 0x56, 0xe8, 0xc8, 0x39, 0xeb, 0x55,
	0xa9, 0x99, 0x0e, 0x30, 0xa8, 0x70, 0x6a, 0x42, 0x59, 0xbf, 0xc2, 0xb1, 0x39, 0x66, 0x83, 0x2a,
	0x0b, 0x8b, 0x44, 0x36, 0xe4, 0xcf, 0x80, 0x6f, 0x29, 0xd1, 0x78, 0xc4, 0x87, 0xf4, 0xf7, 0xc2,
	0x27, 0xa2, 0xd8, 0xf8, 0xaa, 0x43, 0x7f, 0x6f, 0x3e, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb6,
	0x69, 0x97, 0x89, 0xeb, 0x08, 0x00, 0x00,
}
