// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalPort(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function ClosePort(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function ConnectRemote(arg1:string):Promise<{[key: string]: any}>;

export function DelLocalPort(arg1:number):Promise<{[key: string]: any}>;

export function DisConnectRemote(arg1:string):Promise<{[key: string]: any}>;

export function GetConnectedPorts(arg1:string):Promise<{[key: string]: any}>;

export function GetLocalPortList():Promise<{[key: string]: any}>;

export function GetPortConfig(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function GetRemotePortList(arg1:string):Promise<{[key: string]: any}>;

export function OpenPort(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<{[key: string]: any}>;

export function SetPortConfig(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;
