// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalPort(arg1, arg2) {
  return window['go']['main']['SerialApp']['AddLocalPort'](arg1, arg2);
}

export function ClosePort(arg1, arg2) {
  return window['go']['main']['SerialApp']['ClosePort'](arg1, arg2);
}

export function ConnectRemote(arg1) {
  return window['go']['main']['SerialApp']['ConnectRemote'](arg1);
}

export function DelLocalPort(arg1) {
  return window['go']['main']['SerialApp']['DelLocalPort'](arg1);
}

export function DisConnectRemote(arg1) {
  return window['go']['main']['SerialApp']['DisConnectRemote'](arg1);
}

export function GetConnectedPorts(arg1) {
  return window['go']['main']['SerialApp']['GetConnectedPorts'](arg1);
}

export function GetLocalPortList() {
  return window['go']['main']['SerialApp']['GetLocalPortList']();
}

export function GetPortConfig(arg1, arg2) {
  return window['go']['main']['SerialApp']['GetPortConfig'](arg1, arg2);
}

export function GetRemotePortList(arg1) {
  return window['go']['main']['SerialApp']['GetRemotePortList'](arg1);
}

export function OpenPort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['SerialApp']['OpenPort'](arg1, arg2, arg3, arg4, arg5);
}

export function SetPortConfig(arg1, arg2, arg3) {
  return window['go']['main']['SerialApp']['SetPortConfig'](arg1, arg2, arg3);
}
