// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClearHisLog():Promise<void>;

export function GetConfig():Promise<any>;

export function GetHisLog():Promise<Array<{[key: string]: any}>>;

export function GetLinkInfos(arg1:string):Promise<Array<any>>;

export function GetPeerState():Promise<number>;

export function GetSystemVersion():Promise<number>;

export function HideWindow():Promise<void>;

export function PullPlatform():Promise<string>;

export function RequestGroupPeers():Promise<Array<any>>;

export function SaveConfig(arg1:any):Promise<string>;

export function SelectPeer(arg1:string):Promise<boolean>;

export function UpdateConfig(arg1:any):Promise<{[key: string]: any}>;

export function UpdatePeers():Promise<void>;

export function UpdateState(arg1:model.PeerState):Promise<void>;

export function UpdateStats(arg1:any):Promise<void>;
