// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHisLog() {
  return window['go']['main']['WailsApp']['ClearHisLog']();
}

export function GetConfig() {
  return window['go']['main']['WailsApp']['GetConfig']();
}

export function GetHisLog() {
  return window['go']['main']['WailsApp']['GetHisLog']();
}

export function GetLinkInfos(arg1) {
  return window['go']['main']['WailsApp']['GetLinkInfos'](arg1);
}

export function GetPeerState() {
  return window['go']['main']['WailsApp']['GetPeerState']();
}

export function GetSystemVersion() {
  return window['go']['main']['WailsApp']['GetSystemVersion']();
}

export function HideWindow() {
  return window['go']['main']['WailsApp']['HideWindow']();
}

export function PullPlatform() {
  return window['go']['main']['WailsApp']['PullPlatform']();
}

export function RequestGroupPeers() {
  return window['go']['main']['WailsApp']['RequestGroupPeers']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['WailsApp']['SaveConfig'](arg1);
}

export function SelectPeer(arg1) {
  return window['go']['main']['WailsApp']['SelectPeer'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['WailsApp']['UpdateConfig'](arg1);
}

export function UpdatePeers() {
  return window['go']['main']['WailsApp']['UpdatePeers']();
}

export function UpdateState(arg1) {
  return window['go']['main']['WailsApp']['UpdateState'](arg1);
}

export function UpdateStats(arg1) {
  return window['go']['main']['WailsApp']['UpdateStats'](arg1);
}
